In [46]:
import pandas as pd 
import numpy as np

In [47]:
df = pd.read_csv("2016.csv")

In [48]:
df.head(5)

,Unnamed: 0,Geo Code,Category,Sub Category,Characteristic_level_1,Characteristic_level_2,Characteristic_level_3,Characteristic_level_4,Counts
0,2630,M1B,Total - Language spoken most often at home for...,Single responses,Official languages,English,NaN,NaN,38755
1,2631,M1B,Total - Language spoken most often at home for...,Single responses,Official languages,French,NaN,NaN,275
2,2633,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Aboriginal languages,NaN,NaN,0
3,2634,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Aboriginal languages,Algonquian languages,NaN,0
4,2635,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Aboriginal languages,Blackfoot,NaN,0

In [49]:
df['Characteristic_level_2'] = np.where(df.Characteristic_level_3.isnull(), df['Characteristic_level_2'], df['Characteristic_level_3'])

In [50]:
df.head(10)

,Unnamed: 0,Geo Code,Category,Sub Category,Characteristic_level_1,Characteristic_level_2,Characteristic_level_3,Characteristic_level_4,Counts
0,2630,M1B,Total - Language spoken most often at home for...,Single responses,Official languages,English,NaN,NaN,38755
1,2631,M1B,Total - Language spoken most often at home for...,Single responses,Official languages,French,NaN,NaN,275
2,2633,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Aboriginal languages,NaN,NaN,0
3,2634,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Algonquian languages,Algonquian languages,NaN,0
4,2635,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Blackfoot,Blackfoot,NaN,0
5,2636,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Cree-Montagnais languages,Cree-Montagnais languages,NaN,0
6,2637,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Cree-Montagnais languages,Cree-Montagnais languages,Atikamekw,0
7,2638,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Cree-Montagnais languages,Cree-Montagnais languages,Montagnais (Innu),0
8,2639,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Cree-Montagnais languages,Cree-Montagnais languages,Moose Cree,0
9,2640,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Cree-Montagnais languages,Cree-Montagnais languages,Naskapi,0

In [61]:
df['Characteristic_level_3'] = np.where(df.Characteristic_level_2 == 'English', 'English', df['Characteristic_level_3'])

In [63]:
df['Characteristic_level_3'] = np.where(df.Characteristic_level_2 == 'French', 'French', df['Characteristic_level_3'])

In [64]:
df.head(5)

,Unnamed: 0,Geo Code,Category,Sub Category,Characteristic_level_1,Characteristic_level_2,Characteristic_level_3,Characteristic_level_4,Counts
0,2630,M1B,Total - Language spoken most often at home for...,Single responses,Official languages,English,English,NaN,38755
1,2631,M1B,Total - Language spoken most often at home for...,Single responses,Official languages,French,French,NaN,275
2,2633,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Aboriginal languages,NaN,NaN,0
3,2634,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Algonquian languages,Algonquian languages,NaN,0
4,2635,M1B,Total - Language spoken most often at home for...,Single responses,Non-official languages,Blackfoot,Blackfoot,NaN,0

In [65]:
newDf = df.dropna(thresh=8)

In [68]:
newDf.to_csv('edited_2016.csv')